version: '2'
services:
  postgres:
    image: postgres:9.4
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_DB=projectapi
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - MAX_CONNECTIONS=300
    volumes:
    - ./scripts:/docker-entrypoint-initdb.d